.TH "brightnesspicker" 1 "Mar 24, 2022" "Screen brightness picker"
.SH "NAME"
brightnesspicker \(em Graphical interface to set the brightness of the screens
.SH "SYNOPSIS"
.PP
\fBbrightnesspicker\fR

.SH "DESCRIPTION"
.PP
Once started this shows a window with a slider per each screen that can be adjusted to change the brightness.
.br
A tray icon is displayed and can be clicked to bring up the selectors again.
.br
This is done because desktop computers can't easily adjust it like laptops and it can be annoying to use the screen's button to change the settings.

.SH "Known issues"
.PP
It does not support wayland. Only Xorg.

.SH "REPORTING BUGS"
.PP
Report all bugs here: <https://github.com/ltworf/brightnesspicker>

.SH "AUTHOR"
.PP
Written by Salvo "LtWorf" Tomaselli

.SH "COPYRIGHT"
.PP
Copyright © 2022 Salvo "LtWorf" Tomaselli. License AGPLv3: GNU Affero GPL version 3 <https://gnu.org/licenses/agpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
